### ISSUE TITLE
Read resolve settings from webpack config

### ISSUE THREAD

**Issue by MrOrz** [storybooks/storyshots#18]
We have some directories other than `node_modules` in `resolve.modules` in our webpack config, including JS and non-JS assets. While non-JS assets can be handled by implementing loaders, we cannot do the same to JS -- implementing JS loaders like `loaders.js = filename => getCorrectPath(filename)` breaks the entire JS loading mechanism.

Projects like [eslint](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack) can read webpack config to resolve JS files while itself does not use webpack at all. Is there any plan to support webpack resolve config, or any work-arounds on the existing imeplementation?

**Comment by arunoda** [comment]
Yes. I think this is something we can do.

**Comment by MrOrz** [comment]
Thanks for the reply.

I have fulfilled my need using [`babel-plugin-module-resolver`](https://github.com/tleunen/babel-plugin-module-resolver) and preparing a `.babelrc` that mimics the webpack's resolve configuration. Here is what it looks like:

``` js
// .storybook/.babelrc
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": [
    ["module-resolver", {
      "root": ["./src"],  // NOTE: it is relative to where you call `npm run test-storybook`, not the directory containing this .babelrc
    }]
  ]
}
```

**Comment by benzaita** [comment]
I just added PR #62 which allows you to use your current webpack configuration.

**Comment by roonyh** [comment]
Since 3.0 we run storyshots within jest. I think jest supports most webpack stuff.

**Comment by benzaita** [comment]
@roonyh can you confirm this actually works in 3.0? It seems to me that Storyshots still can't handle webpack config
