### ISSUE TITLE
Needs reporter support

### ISSUE THREAD

**Issue by MrOrz** [storybooks/storyshots#29]
Currently the test result is directly dumped into process.stdout.
However, in order to integrate with CI, reporters like junit XML formats is required.

**Comment by roonyh** [comment]
Yeah we did not gave it a much thought. And at the moment we are more focused on extending the support for complex webpack setups. So adding an api that support reporters is not a priority.

I think this will not prevent it from using in common CI's like circle ci or travis though? I am not familiar with junit XML formats.

But it would be cool to have reporters working with this. So pull requests are always welcome :)

**Comment by MrOrz** [comment]
Seems that storyshots 3.0.0 is integrated with jest, using jest's reporter, which connects with CI painlessly. Hooray!
