### ISSUE TITLE
Support React-Native

### ISSUE THREAD

**Issue by barakcoh** [storybooks/storyshots#42]
Hi

I have a bunch of stories in my project and `react-native-storybook` is working great. However, when I try to use storyshots (`npm run test-storybook`) I get `ReferenceError: __DEV__ is not defined` presumably because storyshots doesn't actually execute jest (and so doesn't load the `jest-react-native` preset).

Would it be possible to add support for React Native?

**Comment by arunoda** [comment]
@roonyh any plans on this?

**Comment by roonyh** [comment]
I didn't try out storyshots with React Native. I think we can support it. Taking look now.

**Comment by barakcoh** [comment]
great, looking forward to your feedback

**Comment by rmevans9** [comment]
Any update on this? Was just going to try it out and everything fell apart (hard dependency on react-storybook). I would love to see this work with React Native

**Comment by roonyh** [comment]
@rmevans9 We are planning to facilitate running storyshots within jest. See #61. This allows storyshots to be used with RN inside jest. I think since jest works well with RN this is a good approach.

**Comment by rmevans9** [comment]
Perfect - thanks for the update @roonyh!

**Comment by arunoda** [comment]
Guys, we published [Storybook 3](https://github.com/storybooks/storyshots) today as @roonyh mentioned.
I hope we could close this now.
