### ISSUE TITLE
Error: Using babel-preset-react-app requires that you specify NODE_ENV or BABEL_ENV environment variables.

### ISSUE THREAD

**Issue by FranciscoGileno** [storybooks/storyshots#46]
Hi.

I have storybook added in my project and I am trying to add storyshots to it. However I am getting this error:

```
$ npm run test-storybook

Error: Using babel-preset-react-app requires that you specify NODE_ENV or BABEL_ENV environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing preset: "C:\\Projects\\mad-frontend-framework\\veneer\\lib\\node_modules\\babel-preset-react-app\\index.js")
    at Object.<anonymous> (C:\Projects\mad-frontend-framework\veneer\lib\node_modules\babel-preset-react-app\index.js:49:9)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Projects\mad-frontend-framework\veneer\lib\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at Module.module.constructor.require.original (C:\Projects\mad-frontend-framework\veneer\lib\node_modules\require-middleware\lib\require-middleware.js:32:21)
    at Module.module.constructor.require (C:\Projects\mad-frontend-framework\veneer\lib\node_modules\require-middleware\lib\require-middleware.js:28:69)
```

Here is part of my package.json

```
  "devDependencies": {
    "@kadira/storybook": "2.21.0",
    "@kadira/storyshots": "2.0.1",
    "babel-cli": "6.16.0",
    "babel-preset-es2015": "6.16.0",
    "babel-preset-react": "6.16.0",
    "babel-preset-stage-2": "6.17.0",
    "gulp": "3.9.1",
    "gulp-exec": "2.1.2",
    "gulp-replace": "0.5.4",
    "md5-file": "3.1.1",
    "node-sass": "3.10.1",
    "rimraf": "2.5.4"
  },
  "scripts": {
    "storybook": "start-storybook -p 6006",
    "test-storybook": "storyshots"
  },
```

And my config.js

```
import { configure } from '@kadira/storybook';

const req = require.context('../stories', true);

function loadStories() {
  req.keys().forEach((filename) => req(filename));
}

configure(loadStories, module);
```

Any clue? Thanks.

**Comment by roonyh** [comment]
Sorry about the late response. For now you can do `NODE_ENV=test npm run test-storybook`. I will look into this.

**Comment by FranciscoGileno** [comment]
Thanks.

It solved the issue, but it is not running any test.

```
Test Summary
> 0 stories tested.
```

Even though I have some stories created and running on Storybook. Am I missing something?

**Comment by roonyh** [comment]
Could you try updating storyshots to the latest version? That might fix this.
Also could you give me the content of your `.storybook/config.js` file?

**Comment by FranciscoGileno** [comment]
I updated storybook and storyshots, and the issue persists:

```
    "@kadira/storybook": "2.29.3",
    "@kadira/storyshots": "2.0.1",
```

And my config is:

```
import { configure } from '@kadira/storybook';

const req = require.context('../stories', true);

function loadStories() {
  req.keys().forEach((filename) => req(filename))
}

configure(loadStories, module);
```

I quick update on this, changing the config to the static version worked:

```
import { configure } from '@kadira/storybook';

function loadStories() {
  require('../stories/icon.stories.js');
}

configure(loadStories, module);
```

Since I have many stories, it would be better loading them automatically, but that seems to break storyshots.

Thanks for your feedback.

**Comment by roonyh** [comment]
There was a small bug with the default regexp of `require.context`. Thanks for reporting :) Fixed it in #55. Version 2.0.2 should work fine for you. Could you try updating to it?

Also 2.0.2 sets the `NODE_ENV` by default. So you dont have to set it manually. Just `npm run test-storybook` should work.

**Comment by FranciscoGileno** [comment]
It worked! Thank you very much!

**Comment by cjpete** [comment]
Why is this restricted to just "development", "test", and "production"? What about QA/staging/preproduction deployments? 

This seems unnecessarily restrictive, given that NODE_ENV could be any variation in many projects (dev, develop, prod, production).

**Comment by ToniChaz** [comment]
I have the same question. Why is this restricted? I have six environments and i cant´t configured .
