### ISSUE TITLE
Error when `.shot` file contains a story that isn't present

### ISSUE THREAD

**Issue by AsaAyers** [storybooks/storyshots#47]
As we saw in #34, Jest will complain if there are extra snapshots. It would be very helpful if Storyshots would do the same.

In one of my projects a story was removed in one PR, but we didn't run storyshots with `-u`. Now a few PRs later the `.shots` files picked up that change.

**Comment by SpaceK33z** [comment]
This is no longer relevant since v3.0, since it now uses Jest for snapshotting.
