### ISSUE TITLE
Ignore .md, .mdown .markdown as well

### ISSUE THREAD

**Issue by ericclemmons** [storybooks/storyshots#49]
These are common extensions when using addons that include markdown files, but need to be ignored when running `storyshots`.

**Comment by roonyh** [comment]
You can provide [custom loaders](https://github.com/kadirahq/storyshots#provide-custom-loaders) for those. If you are proposing they should be handled by default, a PR with a suitable mock loader is most welcome :) https://github.com/kadirahq/storyshots/blob/master/src/default_config/loaders.js

**Comment by ericclemmons** [comment]
Thanks @roonyh!  I like to open issues before submitting PRs to ensure I don't violate scope of the project.

(I have several OSS projects myself)

Since this is a welcome change, I'll work on a PR.  Thanks!
