### ISSUE TITLE
Importing jpg,png,gif,etc uses an absolute path

### ISSUE THREAD

**Issue by AsaAyers** [storybooks/storyshots#51]
Storybook is saying that one of my stories is failing because the path changed:

```patch
-         src="/Users/erik/projects/project-name/browser/assets/svgs/cs-folder.svg" />
+         src="/home/asa/projects/project-name/browser/assets/svgs/cs-folder.svg" />
```

I was able to fix it with a custom loader, but I think this should work by default. I'd open a PR, but I don't know how to find `projectRoot` in a way that should work consistently across projects.

```js
const path = require('path')
const projectRoot = path.join(__dirname, '../')

const fileExts = ['jpg', 'png', 'gif', 'eot', 'svg', 'ttf', 'woff', 'woff2'];
const moduleExts = ['css', 'scss', 'sass'];

const loaders = {};

fileExts.forEach((ext) => {
    loaders[ext] = filename => path.relative(projectRoot, filename)
});

moduleExts.forEach((ext) => {
    loaders[ext] = () => null;
});

module.exports = loaders;
```

**Comment by ericclemmons** [comment]
I agree.  @AsaAyers what I've been using is stripping `process.cwd()` from the paths.  Works perfectly!

I just submitted a PR ( #56 ) that will setup scaffolding to make it easier to   work on this.

However, it _would_ be considered a breaking change, but deservedly so.

**Comment by roonyh** [comment]
storyshots use jest from 3.0. Jest [seems to handle](https://facebook.github.io/jest/docs/tutorial-webpack.html) this properly. Will close since we are moving forward with 3.0's way of running storyshots.
