### ISSUE TITLE
.addDecorator is probably not working

### ISSUE THREAD

**Issue by kitze** [storybooks/storyshots#68]
I'm using material-ui in my project for some of the components. The components that are not affected by material-ui and don't need muiTheme pass the tests. But the other components that need muiTheme provided by context, are failing with a warning ```Warning: Failed context type: The context `muiTheme` is marked as required in `CircularProgress`, but its value is `undefined`.```

Keep in mind that the stories in storybook are fine because I'm providing muiTheme through a decorator like this in my global .storybook/config.js file:

```
addDecorator(story => wrapWithStyles(story()));
addDecorator(story => wrapWithMui(story()));
```

**Comment by arunoda** [comment]
@roonyh what do you think about this issue?

**Comment by roonyh** [comment]
@kitze I am taking a look. `addDecorator` works with simple wrappers but I guess something does not work with `context`. Have you used storyshots `2.x` versions successfully with your stories?

**Comment by fredantell** [comment]
I'm running into the same issue. I have a <ContextProvider /> component I specifically created for testing. I can use a global addDecorator and it works fine with storybooks. Then when I run storyshot via jest it fails trying to find functions that should have been injected via context.

If I use addDecorator on a per story level it works fine in both storybooks and storyshots.
Similarly if I just wrap each story directly in the <ContextProvider /> component that also works fine for both storybook and storyshots.

**Comment by jacobk** [comment]
I have this issue too with storyshots `3.2.2`.
