### ISSUE TITLE
create-react-app

### ISSUE THREAD

**Issue by lifeiscontent** [storybooks/storyshots#71]
When using a default create-react-app for storyshots, it seems to break.

I've got this code in `src/Storyshots.test.js`

``` es6
import initStoryshots from 'storyshots';
initStoryshots();
```

the error in the test is

``` bash
Test suite failed to run

    evalmachine.<anonymous>:1
    (function (exports, require, module, __filename, __dirname) { import { configure } from '@kadira/storybook';
                                                                  ^^^^^^
    SyntaxError: Unexpected token import
```

**Comment by lifeiscontent** [comment]
figured it out, I needed a `.babelrc` that reflected the same presets as create react app

**Comment by roonyh** [comment]
Glad it works! storyshots comes pre transpiled. So I think this is unrelated to storyshots. Anyway reopen if needed.

**Comment by kedoska** [comment]
I have the same issue.
@lifeiscontent where did you set up the `.babelrc`?

in my `__tests__` directory i have one file, _storyshots.js_

```javascript
import initStoryshots from 'storyshots'
initStoryshots({
  suit: 'ComponentStories'
})
```

when i run `npm run test-storybook` everything works just fine
but, when i run _npm test_ or, in my case `CI=true npm test` it fails like this

![screenshot from 2017-01-12 15 35 31](https://cloud.githubusercontent.com/assets/11739105/21907240/c47a1572-d8dc-11e6-91d2-44ebc26b6f74.png)

my project was created with `create-react-app`

**Comment by Fatxx** [comment]
Any solution here? Get in the same error

**Comment by Fatxx** [comment]
Could this issue be related to the command `react-scripts test --env=jsdom` ? Which we use to run tests?

**Comment by marc-rutkowski** [comment]
@kedoska, @Fatxx, as mentioned by @lifeiscontent, providing a basic `.babelrc` file (containing the following snippet) into the project root folder, solves the problem.

```
{
  "presets": ["es2015", "react"]
}

```

Let us know if it works for you.

**Comment by irnc** [comment]
Please have a look at https://github.com/storybooks/storyshots/pull/67#pullrequestreview-26933230 which added code related to babel config. The root cause for that issue seems to be in usage of `babelConfig` variable before its declaration.

**Comment by baptistemanson** [comment]
We were not able to get storyshots working at the same time as storybook and create-react-app using the workaround.
:(.

**Comment by irnc** [comment]
@baptistemanson For a workaround, you could move from ES6 to ES5 in `.storybook/config.js`, i.e. use `requite` instead of `import`, so unconfigured Babel would just pass without an error on unknown syntax.

Note, that original error is about unknown syntax in `.storybook/config.js`, not in `Storyshots.test.js`.
