### ISSUE TITLE
Could not run tests exit with "dataId is not supplied via queryString"

### ISSUE THREAD

**Issue by felquis** [storybooks/storyshots#77]
How to reproduce
```
git clone git@github.com:felquis/webpack.git
```
Then install deps `yarn`

Run `yarn test` then you will see.
![screen shot 2017-01-29 at 3 57 39 am](https://cloud.githubusercontent.com/assets/736728/22402279/c8fd783e-e5d7-11e6-9c9e-dddd239732c5.png)

Im not sure what is going on.

**Comment by botteu** [comment]
I have the same problem. I don't know where to look…
