### ISSUE TITLE
use with addons result in big snapshots

### ISSUE THREAD

**Issue by macrozone** [storybooks/storyshots#78]
when using with react-storybook-addon-info or decorators, the snapshot 
will include the markup of these addons as well. This makes it harder to see the differences when a test fails. Is it possible to exclude addons from the snapshot?

**Comment by marc-rutkowski** [comment]
Hello @macrozone ,

And sorry for the following shameless self-promotion...

I don't have found any solution for the problem when using decorators, but maybe you will want to try a [new addon](https://github.com/marc-rutkowski/storybook-addon-props) to replace addon-info.
Just publish it as a quick experimentation a few days ago and I will be very interested to have some feedback about it.

The creation of this addon was inspired [by this issue](https://github.com/storybooks/react-storybook-addon-info/issues/67#issuecomment-247491057).

**Comment by macrozone** [comment]
hi @marc-rutkowski thank you for your addon, i tested it, but it did not work (cannot read property "description" of undefined). There seems to be something not compatible. (filled an issue)

**Comment by marc-rutkowski** [comment]
Thanks for testing it!
See my response into [the issue](https://github.com/marc-rutkowski/storybook-addon-props/issues/1).

**Comment by 7rulnik** [comment]
@macrozone @marc-rutkowski  you can disable your addons and decorators when running jest and mock react-storybook-addon-info.

```js
import { configure, setAddon, addDecorator } from '@kadira/storybook'
import centered from '@kadira/react-storybook-decorator-centered'
import infoAddon from '@kadira/react-storybook-addon-info'

import React from 'react'

if (process.env.NODE_ENV === 'test') { // or your custom env
  setAddon({
    addWithInfo(storyName, info, StoryFn) {
      return this.add(storyName, () => <StoryFn />)
  })
} else {
  setAddon(infoAddon)
  addDecorator(centered)
}

const req = require.context('../components', true, /stories.js$/)
const loadStories = () => req.keys().forEach((filename) => req(filename))

configure(loadStories, module)
```

**Comment by macrozone** [comment]
@7rulnik: thank you very much, that's the solution!
