### ISSUE TITLE
storyshots example not working only leads to error

### ISSUE THREAD

**Issue by bitflorist** [storybooks/storyshots#88]
FAIL  ./Storyshots.test.js Test suite failed to run

    Cannot find module '../../package' from 'node.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/babel-core/lib/api/node.js:60:16)

anyone has a clue / hint if this is a failure of implementation or a bug?
thnx a lot!

**Comment by eric-burel** [comment]
Don't forget to add json as a valid module extension in your jest config:
`
    "moduleFileExtensions": [
      "js", "jsx", "ts", "tsx", "json"
    ],
`
Indeed you can see in `babel-core` code that it loads the root `package.json` file.
