### ISSUE TITLE
Add regex to match the story's kind

### ISSUE THREAD

**Issue by olistic** [storybooks/storyshots#91]
What do you guys think about having these two config options: `storyKindRegex` and `storyNameRegex` instead of the current `storyRegex`?

`storyNameRegex` would behave just as the existing `storyRegex`, while `storyKindRegex` would match against the story's kind, giving users more flexibility.

For example, it could be used to solve #84 doing something like this:

```javascript
// SomeComponent.stories.js

// ...
storiesOf('SomeComponent', module)
    .add('foo', () => {
        // ...
    });
```

```javascript
// SomeComponent.test.js

import initStoryshots from 'storyshots';

initStoryshots({
  storyKindRegex: /^SomeComponent$/,
});
```

Which will cause storyshots (or jest actually) to output a `__snapshots__` directory colocated with the component and with just its storyshots.

If you think it is a good idea, I'm happy to submit a PR!

**Comment by olistic** [comment]
I guess I'm submitting the PR anyway, it's simple enough and I need it for my projects.

**Comment by alex35mil** [comment]
Why not just writing snapshots next to the stories file? W/o dummy regexp for each component.
